Fix release flow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -14,7 +14,7 @@ permissions: {}
 
 jobs:
   prepare:
-    name: Prepare Release
+    name: Prepare release
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -61,6 +61,15 @@ jobs:
             fi
           } | tee "$GITHUB_OUTPUT"
 
+      - name: Sanity check
+        shell: bash
+        run: |
+          # Ensure version matches semver (e.g., 1.2.3, 1.2.3-beta.1)
+          if ! [[ "${{ steps.info.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
+            echo "Error: Version '${{ steps.info.outputs.version }}' does not match SemVer format (e.g., 1.2.3 or 1.2.3-beta.1)."
+            exit 1
+          fi
+
       - name: Generate changelog
         uses: orhun/git-cliff-action@v4
         id: git-cliff
@@ -72,7 +81,7 @@ jobs:
           GIT_CLIFF_CONFIG_URL: https://raw.githubusercontent.com/orhun/git-cliff/refs/heads/main/examples/github.toml
 
   release:
-    needs: changelog
+    needs: prepare
     name: "Release"
     runs-on: "ubuntu-latest"
     permissions:
